import Head from 'next/head'
import redirect from 'nextjs-redirect'
import styles from '../styles/Home.module.css'

export default function Home() {
    const Redirect = redirect('https://github.com/neckalas')
    return (
        <Redirect>
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.loader}>
                <div className={styles.loader__circle}>
                    <div className={styles.loader__line}>

                    </div>
                </div>
            </div>
            <h1>Loading...</h1>
        </div>
        </Redirect>
    )
}
